spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://127.0.0.1:3306/carmall??serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379


#小程序认证配置
wechatmini:
  #appid
  appId: wx6facec47c2fca33b
  #secret
  secret: 65568ccf41d0e3ed967d547bf1e71166
  #code获取openid连接
  authUrl: https://api.weixin.qq.com/sns/jscode2session

